import { useState, useRef } from 'react'
import { useToast } from '@/hooks/use-toast'
import { Plan, Task, LearningEntry, CodeGenType, TestType } from '../types'

export function useRalphLoop() {
  const { toast } = useToast()

  // Plan Mode State
  const [requirementsInput, setRequirementsInput] = useState('')
  const [currentPlan, setCurrentPlan] = useState<Plan | null>(null)
  const [isGeneratingPlan, setIsGeneratingPlan] = useState(false)
  const [allPlans, setAllPlans] = useState<Plan[]>([])
  const [activeTab, setActiveTab] = useState<'plan' | 'execute' | 'generate' | 'learning' | 'servers'>('plan')

  // Execute Mode State
  const [executingPlan, setExecutingPlan] = useState<Plan | null>(null)
  const [isExecuting, setIsExecuting] = useState(false)
  const [currentTaskIndex, setCurrentTaskIndex] = useState(0)
  const [executionLog, setExecutionLog] = useState<string[]>([])
  const [executionSummary, setExecutionSummary] = useState<string>('')
  const [showExecutionSummary, setShowExecutionSummary] = useState(false)

  // Learning State
  const [learningEntries, setLearningEntries] = useState<LearningEntry[]>([])
  const [totalTokensUsed, setTotalTokensUsed] = useState(0)
  const [successRate, setSuccessRate] = useState(0)

  // Generate Code State
  const [codeGenType, setCodeGenType] = useState<CodeGenType>('typescript')
  const [generatedCode, setGeneratedCode] = useState('')
  const [isGeneratingCode, setIsGeneratingCode] = useState(false)
  const [codeGenError, setCodeGenError] = useState('')
  const [codeGenSuiteName, setCodeGenSuiteName] = useState('')
  const [codeGenAppName, setCodeGenAppName] = useState('')
  const [codeGenBaseUrl, setCodeGenBaseUrl] = useState('')
  const [codeGenTestType, setCodeGenTestType] = useState<TestType>('UI')
  const [codeGenTestName, setCodeGenTestName] = useState('')
  const [hasAutoGeneratedTs, setHasAutoGeneratedTs] = useState(false)

  // Code Validation State
  const [isValidatingCode, setIsValidatingCode] = useState(false)
  const [validationResults, setValidationResults] = useState<string[]>([])
  const [validationSuccess, setValidationSuccess] = useState<boolean | null>(null)
  const [autoFixAttempts, setAutoFixAttempts] = useState(0)
  const maxAutoFixAttempts = 10
  const [healerAttempts, setHealerAttempts] = useState(0)
  const maxHealerAttempts = 10

  // MCP Servers State
  const [mcpServers, setMcpServers] = useState<any[]>([])
  const [mcpStatuses, setMcpStatuses] = useState<Record<string, any>>({})
  const [mcpTools, setMcpTools] = useState<any[]>([])
  const [connectingServers, setConnectingServers] = useState<Set<string>>(new Set())

  const logRef = useRef<HTMLDivElement>(null)

  // Computed values
  const completedCount = executingPlan 
    ? executingPlan.generatedTasks.filter(t => t.status === 'completed').length 
    : 0
  const totalCount = executingPlan?.generatedTasks.length || 0

  return {
    // State
    requirementsInput,
    setRequirementsInput,
    currentPlan,
    setCurrentPlan,
    isGeneratingPlan,
    setIsGeneratingPlan,
    allPlans,
    setAllPlans,
    activeTab,
    setActiveTab,
    executingPlan,
    setExecutingPlan,
    isExecuting,
    setIsExecuting,
    currentTaskIndex,
    setCurrentTaskIndex,
    executionLog,
    setExecutionLog,
    executionSummary,
    setExecutionSummary,
    showExecutionSummary,
    setShowExecutionSummary,
    learningEntries,
    setLearningEntries,
    totalTokensUsed,
    setTotalTokensUsed,
    successRate,
    setSuccessRate,
    codeGenType,
    setCodeGenType,
    generatedCode,
    setGeneratedCode,
    isGeneratingCode,
    setIsGeneratingCode,
    codeGenError,
    setCodeGenError,
    codeGenSuiteName,
    setCodeGenSuiteName,
    codeGenAppName,
    setCodeGenAppName,
    codeGenBaseUrl,
    setCodeGenBaseUrl,
    codeGenTestType,
    setCodeGenTestType,
    codeGenTestName,
    setCodeGenTestName,
    hasAutoGeneratedTs,
    setHasAutoGeneratedTs,
    isValidatingCode,
    setIsValidatingCode,
    validationResults,
    setValidationResults,
    validationSuccess,
    setValidationSuccess,
    autoFixAttempts,
    setAutoFixAttempts,
    maxAutoFixAttempts,
    healerAttempts,
    setHealerAttempts,
    maxHealerAttempts,
    mcpServers,
    setMcpServers,
    mcpStatuses,
    setMcpStatuses,
    mcpTools,
    setMcpTools,
    connectingServers,
    setConnectingServers,
    logRef,
    completedCount,
    totalCount,
    toast
  }
}
