name: Build & Package Portable Next.js App

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-portable:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build Next.js app
        run: npm run build

      - name: Run PowerShell packaging script
        shell: pwsh
        run: ./prepare-distribution.ps1

      - name: Zip dist-app folder
        run: powershell Compress-Archive -Path dist-app/* -DestinationPath portable-nextjs.zip

      - name: Upload zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: portable-nextjs
          path: portable-nextjs.zip
